# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-all

on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
     - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven and upload coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        ls -lah
        mvn clean package -Pcoverage
        ls -lah
        ls -lah target
        ls -lah target/site
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report
